### ISSUE TITLE
haxelib installation fails (state of thx.core dependency)?

### ISSUE THREAD

**Issue by milkmangames** [ufront/ufront#20]
I'm looking to run the ufront hello demo and get started with a new ufront project using the latest and greatest.  Installing from haxelib using directions in ufront hello's readme.

Building the app fails due to thx.core not found (ex. HaxeToolkit\haxe\lib\ufront-mvc/1,0,0-rc,15/src/ufront/app/UfrontApplication.hx:3: characters 7-34 : Class not found
: thx.core.error.NullArgument).

I see in the git commit logs recent changes around removing the thx.core dependencies.  Do I need to checkout all the ufront modules from git to be able to use it?  If so is there an effective way to do this with dependency management, or do I need to get git versions of all dependencies and set them with haxelib dev?  [Sorry if I'm missing something obviosu!)

**Comment by milkmangames** [comment]
i've gone through and switched all dependent libraries to use the latest git master (and in the case of minject, the branch with most recent changes.)

Seems like some haxelib dependencies are missing from the hxml (example, '-lib mcli' should be in tasks.hxml.)

Most errors are cleared but there are still issues with EasyAuth, UfrontMail, and UfrontAdmin.  Not sure if these have not been updated yet in github to work with the latest versions of other libs (seems like maybe they depend on a different version of minject than some of the others.)

**Comment by kevinresol** [comment]
I think ufront no longers depends on thx.* libraries.
