### ISSUE TITLE
Proposal on lib structure

### ISSUE THREAD

**Issue by kevinresol** [ufront/ufront#24]
| Lib | Importance | Remarks |
| --- | --- | --- |
| mvc | high | this is core "ufront" |
| orm | medium | a plugin |
| client | low | actually it is just mvc + orm + some supporting lib for js (e.g. pushstate) |
| easy-auth | low | a plugin |
| mail | low | a plugin |
- Importance indicates the importance in the lib dependency tree, not the actual usage.

What I want to suggest here is to only set explicit version for the dependencies in ufront-mvc and other ufront-\* lib set ufront-mvc as their dependency. This is to resolve the dependency hell. Also make it easier to install, as they are nicely separated.

git submodule is not a good idea because `haxelib update ufront` will not update the submods

(This is posted in a hurry, sorry for not expressing my idea clearly. We can discuss further.)

**Comment by kevinresol** [comment]
I think the very first thing to do is to remove all the explicit versions in haxelib.json in github, but only add them back in a release. That would first solve the problem of not able to use the newest git dev version of the libs.

ref. https://github.com/HaxeFoundation/haxe.org/issues/151

**Comment by kevinresol** [comment]
@ufront/owners I would like to propose the following changes.

## Background

ufront/ufront is:

- a `haxelib.json` that brings together the following libs, so when you `-lib ufront` you will get'em all
  - `ufront-mvc` 
  - `ufront-orm` 
  - `ufront-easyauth`
- an `extraParams.hxml` that defines `-D server`
- a set of ufront tools (e.g. `ufront b`, `ufront s`, etc)
- holds other ufront libs as submodules and run tests on them

ufront/ufront-client is:

- a `haxelib.json` that brings together the following libs, so when you `-lib ufront-client` you will get'em all
  - `ufront-mvc` 
  - `ufront-orm` 
  - `ufront-easyauth` 
  - `pushstate`
- an `extraParams.hxml` that defines `-D client`


## Problems

In my opinion, using `-lib ufront` and `-lib ufront-client` causes a few problems:

0. hard to update the individual libs (`haxelib update ufront` won't update your submodules)
0. hard to switch version of individual lib (because the version is hardcoded in the haxelib.json)
0. hard to sync, need to manually update the submodule ref
0. `ufront-orm` &  `ufront-easyauth` is not compulsory, why include them in the haxelib.json?

## Proposed Solution

0. Remove `ufront/ufront` and `ufront/ufront-client` entirely
  - to use minimal ufront in server, simply need to `-lib ufront-mvc -D server` 
  - to use minimal ufront in client, simply need to `-lib ufront-mvc -lib pushstate -D client`
0. Move ufront tools to a separate lib (say `uftools`)
0. Move tests back to their own repo (under current approach, the tests won't get triggered in the ufront repo anyway, if the change are made in the individual repos)

**Comment by kevinresol** [comment]
@jasononeil I can start doing the dirty work if I have your consent.

**Comment by postite** [comment]
totally agree with your proposal @kevinresol

**Comment by wwhitehead** [comment]
agree as well @kevinresol

**Comment by jasononeil** [comment]
Sounds good @kevinresol ... happy for you to start in this direction :+1:

**Comment by jasononeil** [comment]
Sounds good! Feel free to get started.

**Comment by francescoagati** [comment]
hi. what do you think about separate http handler with request response and context in a seperate library.
Like rack with rails?
Create a rack for haxe that can be used from others libraries.

**Comment by kevinresol** [comment]
@francescoagati are you looking for https://github.com/haxetink/tink_http?

**Comment by francescoagati** [comment]
yes but also create wrappers over connect for node, flask for python, jetty for java ecc....

**Comment by francescoagati** [comment]
but only at low http level.

**Comment by kevinresol** [comment]
I think we can add a "tink_http target" for ufront, and let tink_http to handle the low level stuff

**Comment by francescoagati** [comment]
yes good idea

**Comment by francescoagati** [comment]
monsoon is wrapper around tink_http for example

**Comment by kevinresol** [comment]
@jasononeil Should be done now. I still need your help to take down the `ufront` and `ufront-client` lib from lib.haxe.org and put up the new lib `ufront-tool`.

**Comment by kevinresol** [comment]
Cleaning up my old issues and I think this is no longer needed.
