### ISSUE TITLE
Erazor templates wiki

### ISSUE THREAD

**Issue by RafaelOliveira** [ufront/ufront#6]
Could you update the Erazor templates wiki? I'd like to try Ufront, and that wiki seems to be a good start. I started learning web dev with basic haxe, but I'd like something with more features, like this project.

**Comment by jasononeil** [comment]
Do you want to take a look at this "Hello World" project that shows how to use erazor templates?

See:

https://github.com/ufront/hello
https://github.com/ufront/hello/tree/master/www/view
